apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
  - protocol: TCP
    port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  config : |
    server {
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /usr/share/nginx/html;

      location ~ ^/(status|ping)$ {
          fastcgi_pass php:9000;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
          fastcgi_param SERVER_NAME $hostname;
          include fastcgi_params;
      }

      #location / {
      #    try_files $uri $uri/ /index.php?$query_string;
      #} #removed to avoid 404 on favicon redirect to index.php

      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass php:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
          fastcgi_param SERVER_NAME $hostname;
          fastcgi_param pm.status_path /status;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-www-config
data:
  zzz-www.conf : |
    [www]
    pm.status_path = /status
    ping.path = /ping
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-liveness-probe
data:
  .nginxLivenessProbeTest.html : |
    <html><body><h1>alive</h1></body></html>
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-html
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.0.6
    path: /storage/web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-html
        persistentVolumeClaim:
         claimName: nginx-html
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: php.conf
      - name: nginx-liveness-probe
        configMap:
          name: nginx-liveness-probe
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /.nginxLivenessProbeTest.html
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: nginx-liveness-probe
          mountPath: /usr/share/nginx/html/.nginxLivenessProbeTest.html
          subPath: .nginxLivenessProbeTest.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 4
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      volumes:
      - name: nginx-html
        persistentVolumeClaim:
          claimName: nginx-html
      - name: php-www-config
        configMap:
          name: php-www-config
      containers:
      - name: php
        image: php:7-fpm
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 3
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
        - name: php-www-config
          mountPath: /usr/local/etc/php-fpm.d/zzz-www.conf
          subPath: zzz-www.conf
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
