apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
spec:
  selector:
    app: zabbix-web
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30081
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
spec:
  selector:
    app: zabbix-server
  type: ClusterIP
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    app: zabbix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix
        - name: DB_SERVER_HOST
          value: 192.168.0.6
        - name: ZBX_SERVER_HOST
          value: zabbix-server
        - name: PHP_TZ
          value: "America/Sao_Paulo"
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix
spec:
  selector:
    matchLabels:
      app: zabbix-server
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:latest
        ports:
        - containerPort: 162
          name: snmptrapd
        - containerPort: 10051
          name: zabbix-trapper
        - containerPort: 10052
          name: zabbix-jmx
        env:
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix
        - name: DB_SERVER_HOST
          value: 192.168.0.6
